version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      expo:
        patterns:
          - "expo*"
          - "@expo/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "react-native"
          - "@react-navigation/*"
      testing:
        patterns:
          - "jest"
          - "ts-jest"
          - "@types/*"
          - "typescript"
          - "react-test-renderer"
  - package-ecosystem: "npm"
    directory: "/modules/dns-native"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

